FROM $parent_image

USER  root

LABEL \
  build_host="$build_host"         \
  build_time="$build_time"         \
  debian_release="$debian_release" \
  docker_tag="$docker_tag"         \
  maintainer="$maintainer"         \
  parent_image="$parent_image"     \
  rakudo_tarball="$rakudo_tarball" \
  rakudo_type="$rakudo_type"       \
  rakudo_url="$rakudo_url"         \
  rakudo_version="$rakudo_version" \
  timezone="$timezone"             \
  user_gecos="$user_gecos"         \
  user_gid="$user_gid"             \
  user_homedir="$user_homedir"     \
  user_login="$user_login"         \
  username="$username"             \
  user_shell="$user_shell"         \
  user_uid="$user_uid"

ADD   bin/             /usr/local/bin/
COPY  tmp/build-config /usr/local/bin/rakudo-build-config

RUN   /usr/local/bin/rakudo-build rakudo-build-config

WORKDIR $user_homedir
USER  $user_login

ENV   RAKUDO_VERSION="$rakudo_version"
ENV   PATH=$PATH:/usr/share/perl6/site/bin

ENTRYPOINT ["perl6"]

# vim:ft=Dockerfile

